name: personal-mapCrawler
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp
  - altair
  - appnope
  - arrow-cpp
  - asttokens
  - attrs
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - backcall
  - backports
  - backports.functools_lru_cache
  - blas
  - blinker
  - boost-cpp
  - bottleneck
  - branca
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - comm
  - commonmark
  - cryptography
  - dataclasses
  - debugpy
  - decorator
  - entrypoints
  - executing
  - folium
  - freetype
  - future
  - gflags
  - giflib
  - gitdb
  - gitpython
  - glog
  - grpc-cpp
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets
  - krb5
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libnghttp2
  - libpng
  - libprotobuf
  - libsodium
  - libssh2
  - libthrift
  - libtiff
  - libwebp
  - libwebp-base
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbformat
  - ncurses
  - nest-asyncio
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - orc
  - packaging
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - prompt-toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pure_eval
  - pyarrow
  - pycparser
  - pydeck
  - pygments
  - pympler
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-tzdata
  - python_abi
  - pytz
  - pytz-deprecation-shim
  - pyyaml
  - pyzmq
  - re2
  - readline
  - requests
  - rich
  - semver
  - setuptools
  - six
  - smmap
  - snappy
  - sqlite
  - stack_data
  - streamlit
  - streamlit-folium
  - tk
  - toml
  - toolz
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - tzlocal
  - urllib3
  - utf8proc
  - validators
  - watchdog
  - wcwidth
  - wheel
  - widgetsnbextension
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd

